[workspace.package]
version = "0.0.1"
edition = "2021"
authors = ["Caio Oliveira <caio.vsoliveira23@gmail.com>"]
license = "MIT"
readme = "readme.md"
rust-version = "1.65"

[workspace]
members = [
	"abstract_db_access",
	"utilities"
]

default-members = [
	"abstract_db_access"
]
